version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  binder:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/binder
    depends_on:
      - db
