services:
  db:
    restart: always
    image: postgres:12
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
  binder:
    restart: always
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/binder
    depends_on:
      - db
