version: '3'

services:
  db:
    image: postgres:11.5
  binder:
    build:
      context: ./
      dockerfile: docker/binder/Dockerfile
    command: tail -f /dev/null
    volumes:
      - .:/binder
    depends_on:
      - db
      - mysql
      - mssqldb
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
  mssqldb:
    build:
      context: ./
      dockerfile: docker/mssqldb/Dockerfile
    environment:
      ACCEPT_EULA: y
      SA_PASSWORD: '~Test123'
    ports:
      - 1433:1433