# Generated by Django 2.2 on 2019-04-25 09:18

import binder.plugins.token_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0003_change_token_to_varchar_for_mysql_compat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=binder.plugins.token_auth.models.generate_token, max_length=64, unique=True),
        ),
    ]
