version: '3'

services:

  db:
    image: postgres:11.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./binder:/code/binder
      - ./testapp:/code/testapp
    ports:
      - "8000:8000"
    depends_on:
      - db
